language: python
python:
    - "2.7"
    - "3.6"
install:
    - pip install coveralls
    - pip install .
    - python -c "import seminario; print(seminario.__version__)"
script:
    - pytest
after_success:
    - cd tests
    - coverage run --source=seminario test_basics.py
    - coveralls
