language: python
python:
    - "2.7"
    - "3.6"
install:
    - pip install pytest
    - pip install pytest-cov
    - pip install coveralls
    - pip install .
    - python -c "import seminario; print(seminario.__version__)"
script:
    - pytest --cov=seminario/
after_success:
    - coveralls
